### ISSUE TITLE
Meta Box Group error: 4.9.2

### ISSUE THREAD

**Issue by billreed85** [rilwis/meta-box#967]
Getting an error with the Meta boxes that have groups in them:

> Notice: Undefined index: field_name in /Users/breed/Desktop/Development/wp/wp-content/plugins/meta-box-group/class-rwmb-group-field.php on line 61
> 
> Fatal error: Uncaught Error: Call to undefined method RW_Meta_Box::get_class_name() in /Users/breed/Desktop/Development/wp/wp-content/plugins/meta-box-group/class-rwmb-group-field.php:63 Stack trace: #0 /Users/breed/Desktop/Development/wp/wp-content/plugins/meta-box/inc/field.php(474): RWMB_Group_Field::html(Array, Array) #1 /Users/breed/Desktop/Development/wp/wp-content/plugins/meta-box/inc/clone.php(49): RWMB_Field::call(Array, 'html', Array) #2 /Users/breed/Desktop/Development/wp/wp-content/plugins/meta-box/inc/field.php(50): RWMB_Clone::html(Array, Array) #3 /Users/breed/Desktop/Development/wp/wp-content/plugins/meta-box/inc/field.php(474): RWMB_Field::show(Array, true) #4 /Users/breed/Desktop/Development/wp/wp-content/plugins/meta-box/inc/meta-box.php(178): RWMB_Field::call('show', Array, true) #5 /Users/breed/Desktop/Development/wp/wp-admin/includes/template.php(1045): RW_Meta_Box->show(Object(WP_Post), Array) #6 /Users/breed/Desktop/Development/wp/wp-a in /Users/breed/Desktop/Development/wp/wp-content/plugins/meta-box-group/class-rwmb-group-field.php on line 63

**Comment by billreed85** [comment]
I didn't update the old version /facepalm
